name: Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '19 20 2 * *'

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: ''
      CARGO_PROFILE_DEV_DEBUG: '0' # reduce size of target directory

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --release --all-targets -- -A clippy::too_many_arguments
